sudo: required
language: python

# Used: travis encrypt "chat.freenode.net#scons" --add notifications.irc
notifications:
  irc:
    secure: TTb+41Bj1qIUc6vj+kDqBME8H3lqXdAe1RWAjjz5hL7bzFah6qCBHNJn4DwzqYs6+Pwuwp+6wFy8hgmQttJnXve4h6GtjtvlWprDqxaC7RkFqMWFDBzDalgbB54Bi4+TTZmSJ1K/duI3LrDaN873nyn+2GBnj+3TiNtgURp1fsJMpPxXJzAsoC8UthEsbx0Zkoal/WF+IfsT2q1yQRmAwB9r/drbahx/FfL16r1QjDbI9y1fKvN5J3PirLUvxtHfuH1r8zq1vlLew2fvldgVRtFv7+Lsk2waG/eiRpMf94V5JWP1rNreV/i4AUbZaTLb3bkrhtvTjSKhvx69Ydm+ygXdRgWOD/KRgqpLNAfA+t/a2J1R++89svQI4dPBpQjlfua1elcDCFddeIslgnjDUPO23Y0o7tHAy8sWkwhTcZH1Wm42uJP6Z6tHTH6+dMLvvZpkq4RUKUcrXvoUvCsVlWMGjcsBX+AEQSFGDJnLtLehO9x0QbgVga/IRKjgpDWgQDZgro3AkGg/zzVj5uFRUoU+rbmEXq9feh5i3HfExAvA3UoEtnQ6uadDyWqtQcLRFmPSWDU82CO+sanGdFL0jBjigE8ubPObzxEAz3Fg1xk56OYBkAdEd+2KEzeO1nqJmrhsnc3c/3+b1cBvaL5ozW4XB4XcWsOi268SoiBrcBo=

services:
  - docker

addons:
  apt:
    update: true

# Note: Travis does not provide a way to specify the order of
# jobs within a Stage, which are "run in parallel", but with
# limitations: from observation four or five are kicked
# off, then additional jobs as initial ones complete.
# We want the slowest jobs in the first batch since the
# faster ones are less than half the time of the slowest,
# we should be able to finish the Test task in the time of the
# slowest job rather than (a fast job + the slowest job).
# Putting the pypy jobs first may help with this, though it's
# apparently not guaranteed.

jobs:

  # pypy is not passing atm, but still report build success for now
  # allow coverage to fail, so we can still do testing for all platforms
  allow_failures:
    - python: pypy3

  include:

    - &test_job
      dist: xenial
      script: python runtest.py -a -t -j 2 -f .travis/non_docker_tests.txt || if [[ $? == 2 ]]; then true; else false; fi
      before_script: skip
      after_success: skip
      python: pypy3

    - <<: *test_job
      python: 3.5

    - <<: *test_job
      python: 3.6

    - <<: *test_job
      python: 3.7

    - <<: *test_job
      python: 3.8
      dist: bionic  # required for Python >= 3.8

    - <<: *test_job
      python: 3.9
      dist: focal  # required for Python >= 3.8

    - &docker_job
      name: Docker - Python3.9 Ubuntu 20.04
      python: 3.9
      before_install:
        - docker pull dmoody256/scons_test_image:ubuntu20
        - docker run -it -d --name build -e PYCOVERAGE=1 -v $PWD:/scons dmoody256/scons_test_image:ubuntu20 bash
      script:
        - sed -e "s#\$PWD#/scons#" .coverage_templates/.coveragerc.template > .coveragerc
        - docker exec build default_python -m virtualenv venv
        - docker exec build /venv/bin/python -m pip install coverage codecov
        - docker exec -w /scons build /venv/bin/python -m coverage run -p --rcfile=/scons/.coveragerc runtest.py -t test/virtualenv/unactivated/virtualenv_unactivated_python.py
        - docker exec -w /scons build bash -c "source /venv/bin/activate && /venv/bin/python -m coverage run -p --rcfile=/scons/.coveragerc runtest.py -t -j 2 -f .travis/virtual_env_tests.txt"
        - docker exec -w /scons build default_python -m coverage run -p --rcfile=/scons/.coveragerc runtest.py -a -t -j 2 --exclude-list .travis/non_docker_tests.txt || if [[ $? == 2 ]]; then true; else false; fi
        - docker exec -w /scons build coverage combine
        - docker exec -w /scons build coverage report -i
        - docker exec -w /scons build coverage xml -i -o coverage_xml.xml
        - docker exec -w /scons build codecov -X gcov --file coverage_xml.xml

    - <<: *docker_job
      python: 3.8
      name: Docker - Python3.8 Ubuntu 18.04
      before_install:
        - docker pull dmoody256/scons_test_image:ubuntu18
        - docker run -it -d --name build -e PYCOVERAGE=1 -v $PWD:/scons dmoody256/scons_test_image:ubuntu18 bash

    - <<: *docker_job
      python: 3.7
      name: Docker - Python3.7 Ubuntu 16.04
      before_install:
        - docker pull dmoody256/scons_test_image:ubuntu16
        - docker run -it -d --name build -e PYCOVERAGE=1 -v $PWD:/scons dmoody256/scons_test_image:ubuntu16 bash

    - <<: *docker_job
      python: 3.6
      name: Docker - Python3.6 Ubuntu 14.04
      before_install:
        - docker pull dmoody256/scons_test_image:ubuntu14
        - docker run -it -d --name build -e PYCOVERAGE=1 -v $PWD:/scons dmoody256/scons_test_image:ubuntu14 bash



